name: Publish Scheduled Posts

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish scheduled posts
        run: |
          curl -X GET "${NEXT_PUBLIC_APP_URL}/api/cron/publish-scheduled" \
          -H "Authorization: Bearer ${CRON_SECRET}"
        env:
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }} 